import AppKit
import Foundation

/// The app that owned the front window when a copy happened.
struct SourceApp {
    let bundleID: String?
    let name: String?
}

/// Watches the general pasteboard and hands new content to the store.
///
/// `NSPasteboard` has no change notification, so like every clipboard manager
/// this polls `changeCount` — cheap, since it is a single integer read.
@MainActor
final class PasteboardMonitor {
    private let store: ClipboardStore
    private let settings: Settings
    private let pasteboard = NSPasteboard.general
    private var timer: Timer?
    private var lastChangeCount: Int

    /// Set by the paster around its own write so the item it just put on the
    /// pasteboard does not come straight back in as a new copy.
    var suppressedFingerprint: String?

    /// Marker types defined by http://nspasteboard.org — the convention apps
    /// use to tell clipboard managers what not to keep.
    private static let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    init(store: ClipboardStore, settings: Settings) {
        self.store = store
        self.settings = settings
        lastChangeCount = pasteboard.changeCount
    }

    func start(interval: TimeInterval = 0.35) {
        stop()
        let timer = Timer.scheduledTimer(withTimeInterval: interval, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        // Keep polling while a menu is open or a window is being resized.
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let change = pasteboard.changeCount
        guard change != lastChangeCount else { return }
        lastChangeCount = change

        guard let types = pasteboard.types else { return }
        if settings.skipConcealed, types.contains(Self.concealedType) { return }
        if settings.skipTransient,
           types.contains(Self.transientType) || types.contains(Self.autoGeneratedType) { return }

        let source = currentSourceApp()
        if let bundleID = source?.bundleID, settings.ignoredBundleIDs.contains(bundleID) { return }

        // A plain-text payload wins: apps that copy an image often also put a
        // caption or URL on the board, and the text is what the user meant.
        if let string = pasteboard.string(forType: .string),
           !string.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            guard !consumeSuppression(of: ClipboardItem.fingerprint(for: string)) else { return }
            store.addText(string, source: source)
            return
        }

        if let (image, png) = readImage() {
            guard !consumeSuppression(of: ClipboardItem.fingerprint(for: png)) else { return }
            store.addImage(image, pngData: png, source: source)
        }
    }

    /// Suppression is one-shot: it covers the single change our own paste
    /// caused, and then lapses so a later genuine copy of the same content is
    /// still recorded.
    private func consumeSuppression(of fingerprint: String) -> Bool {
        guard suppressedFingerprint == fingerprint else { return false }
        suppressedFingerprint = nil
        return true
    }

    /// Pulls a bitmap off the pasteboard and normalises it to PNG.
    private func readImage() -> (NSImage, Data)? {
        guard let image = NSImage(pasteboard: pasteboard) else { return nil }
        guard let tiff = image.tiffRepresentation,
              let rep = NSBitmapImageRep(data: tiff),
              let png = rep.representation(using: .png, properties: [:])
        else { return nil }
        return (image, png)
    }

    private func currentSourceApp() -> SourceApp? {
        guard let app = NSWorkspace.shared.frontmostApplication else { return nil }
        // Our own popup is never the interesting source.
        if app.bundleIdentifier == Bundle.main.bundleIdentifier { return nil }
        return SourceApp(bundleID: app.bundleIdentifier, name: app.localizedName)
    }
}
